isteps:
  # Step 1: Build the Docker Image and push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildAndPush
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t us-central1-docker.pkg.dev/high-splicer-429006-m7/kommunicate-repo-image:latest .
        docker push us-central1-docker.pkg.dev/high-splicer-429006-m7/kommunicate-repo-image:latest

  # Step 2: Deploy to GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gke-gcloud-auth-plugin --version
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials "testing-cluster" --project "high-splicer-429006-m7" --zone "us-central1"
        kubectl apply -f deploy.yaml
        kubectl apply -f service.yaml

images:
  - 'us-central1-docker.pkg.dev/high-splicer-429006-m7/kommunicate-repo-image:latest'

