steps:
# Step 1: Build the Docker Image and push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - | 
      #!/bin/bash
      docker build -t us-central1-docker.pkg.dev/high-splicer-429006-m7/kommunicate-repo-image:$SHORT_SHA .
      docker push us-central1-docker.pkg.dev/high-splicer-429006-m7/kommunicate-repo-image:$SHORT_SHA

#Step 2: Create the Cloud build  Pipeline for deploy
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      #!/bin/bash
       gke-gcloud-auth-plugin --version
       export USE_GKE_GCLOUD_AUTH_PLUGIN=True
       gcloud container clusters get-credentials "testing-cluster" --project "high-splicer-429006-m7" --zone "us-central1"
       kubectl apply -f deploy.yaml
       kubectl apply -f service.yaml


#availableSecrets:
##secretManager:
#options:
#logging: CLOUD_LOGGING_ONLY
#workerPool: 'projects/push-dev-apps/locations/us-central1/workerPools/worker-pool-d-services-base-usce1'

